-- PostgreSQL production schema reference for Secure Print Platform.
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS users (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), full_name TEXT NOT NULL, shop_name TEXT NOT NULL, email CITEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, phone TEXT, verified BOOLEAN NOT NULL DEFAULT false, role TEXT NOT NULL DEFAULT 'owner', created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS products (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id), product_code TEXT UNIQUE NOT NULL, customer_name TEXT NOT NULL, product_name TEXT NOT NULL, category TEXT NOT NULL DEFAULT 'সাধারণ', file_key TEXT NOT NULL, mime_type TEXT NOT NULL, qr_data TEXT NOT NULL UNIQUE, status TEXT NOT NULL DEFAULT 'active', privacy TEXT NOT NULL DEFAULT 'PRINT-ONLY', print_limit INTEGER NOT NULL DEFAULT 5, print_count INTEGER NOT NULL DEFAULT 0, session_count INTEGER NOT NULL DEFAULT 0, expiry_at TIMESTAMPTZ, deleted_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS product_activity (id BIGSERIAL PRIMARY KEY, product_id UUID NOT NULL REFERENCES products(id), action TEXT NOT NULL, details TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS print_settings (product_id UUID PRIMARY KEY REFERENCES products(id), paper TEXT NOT NULL DEFAULT 'A4', photo_size TEXT NOT NULL DEFAULT '35x45 mm', unit TEXT NOT NULL DEFAULT 'mm', orientation TEXT NOT NULL DEFAULT 'portrait', margin_top NUMERIC NOT NULL DEFAULT 5, margin_bottom NUMERIC NOT NULL DEFAULT 5, margin_left NUMERIC NOT NULL DEFAULT 5, margin_right NUMERIC NOT NULL DEFAULT 5, gap_horizontal NUMERIC NOT NULL DEFAULT 2, gap_vertical NUMERIC NOT NULL DEFAULT 2, copies INTEGER NOT NULL DEFAULT 1, fit TEXT NOT NULL DEFAULT 'fit', dpi INTEGER NOT NULL DEFAULT 300, border BOOLEAN NOT NULL DEFAULT false, crop_marks BOOLEAN NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS print_sessions (id TEXT PRIMARY KEY, product_id UUID NOT NULL REFERENCES products(id), expires_at TIMESTAMPTZ NOT NULL, used BOOLEAN NOT NULL DEFAULT false, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS print_jobs (id BIGSERIAL PRIMARY KEY, product_id UUID NOT NULL REFERENCES products(id), session_id TEXT REFERENCES print_sessions(id), copies INTEGER NOT NULL DEFAULT 1, paper TEXT NOT NULL DEFAULT 'A4', photo_size TEXT NOT NULL DEFAULT '35x45 mm', status TEXT NOT NULL DEFAULT 'READY', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), completed_at TIMESTAMPTZ);
CREATE INDEX IF NOT EXISTS products_user_status_idx ON products(user_id,status,created_at DESC);
CREATE INDEX IF NOT EXISTS activity_product_idx ON product_activity(product_id,created_at DESC);
